databases:
  - name: micro
    databaseName: micro_5iaq
    user: micro_5iaq_user

services:
  - type: web
    name: zola
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: micro
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false