databases:
  - name: mysite
    databaseName: budget_app_production
    user: postgres

services:
  - type: web
    name: mysite
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
